baseURL = "/"
languageCode = "en-us"
title = "✨"
theme = "minimal"
disqusShortname = "dmitriydubson" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Dmitriy Dubson"
    description = " written ✚ curated by Dmitriy Dubson"
    githubUsername = "ddubson"
    accent = "#E65100"
    showBorder = true
    backgroundColor = "#fffbfa"
    profilePic = "/avatar.jpg"
    font = "Inconsolata" # should match the name on Google Fonts!
    css = ["css/extend.css"]
    highlight = true
    disableComments = false
    highlightStyle = "gruvbox-dark"
    highlightLanguages = ["haskell", "kotlin", "java", "typescript", "javascript"]
    copyright = "Made and curated with 🧡 in New York"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/kit/"
    name = "Kit"
    weight = 3

[[menu.main]]
    url = "/garden/"
    name = "The Digital Garden"
    weight = 4 

[[menu.main]]
     url = "https://hackmd.io/@ddubson/B1mQzbCdL"
     name = "Tech Playlist 📻"
     weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/ddubson/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/ddubson1/"
    name = "linkedin"
    weight = 2
